### ISSUE TITLE
Makefile issues

### ISSUE THREAD

**Issue by Mr-Technician** [sunfoxcz/ipmiview#7]
Hey there, I am new to working with makefiles and docker in general, and I have hit a snag.

The instructions aren't that clear. I can't run `make` right after extracting the tarball since it hasn't been downloaded yet, so I tried cloning the makefile manually with wget and then running make. This gave me a different error:

```root@ipmi-docker:~/docker/IPMIView_2.21.0_build.221118_bundleJRE_Linux_x64# make
Makefile:8: *** missing separator.  Stop.
```

Would you be able to help me out here and also clean up the instructions?

**Comment by foxycode** [comment]
@Mr-Technician  Unfortunately, I don't have idea why you see this error. What system do you run on? Have you docker installed?

**Comment by Mr-Technician** [comment]
I am running ubuntu server in a virtual machine. Docker and docker compose are installed.

**Comment by Mr-Technician** [comment]
Ah, I cloned the repo and tried again and it worked. User error on my end!
